package com.fitnesshub.audit;

public enum AuditAction {
    USER_REGISTERED,
    LOGIN,
    LOGIN_FAILED,
    LOGOUT,
    WORKOUT_CREATED,
    WORKOUT_COMPLETED,
    WORKOUT_SKIPPED,
    PROGRAM_CREATED,
    PROGRAM_ASSIGNED,
    PROGRAM_UPDATED,
    WEIGHT_LOGGED,
    NUTRITION_LOGGED,
    STEPS_LOGGED,
    GOAL_CREATED,
    GOAL_UPDATED,
    CHECKIN_SUBMITTED,
    CHECKIN_REVIEWED,
    MESSAGE_SENT,
    AI_REQUESTED,
    SUBSCRIPTION_STARTED,
    SUBSCRIPTION_CANCELLED,
    CLIENT_CREATED,
    COACH_NOTE_CREATED
}
